// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqpsYV1wg2Y58_62sIDsDPq46R0_Vv6Kw',
    appId: '1:632303151235:web:fe313621301479716bd3b6',
    messagingSenderId: '632303151235',
    projectId: 'trobar-1123f',
    authDomain: 'trobar-1123f.firebaseapp.com',
    storageBucket: 'trobar-1123f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqABoWaKcgNGSi8hbGW7LH_pFYUDqnek',
    appId: '1:632303151235:android:20a8592fdabdd1df6bd3b6',
    messagingSenderId: '632303151235',
    projectId: 'trobar-1123f',
    storageBucket: 'trobar-1123f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDFssqooKhWJZ-FGfuawXnX_SPrFz58Fo',
    appId: '1:632303151235:ios:3f993de5cbb65aab6bd3b6',
    messagingSenderId: '632303151235',
    projectId: 'trobar-1123f',
    storageBucket: 'trobar-1123f.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqpsYV1wg2Y58_62sIDsDPq46R0_Vv6Kw',
    appId: '1:632303151235:web:779cd25c11585c6e6bd3b6',
    messagingSenderId: '632303151235',
    projectId: 'trobar-1123f',
    authDomain: 'trobar-1123f.firebaseapp.com',
    storageBucket: 'trobar-1123f.firebasestorage.app',
  );
}
